# coding: utf-8

"""
    Lightly API

    Lightly.ai enables you to do self-supervised learning in an easy and intuitive way. The lightly.ai OpenAPI spec defines how one can interact with our REST API to unleash the full potential of lightly.ai  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@lightly.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from lightly.openapi_generated.swagger_client.configuration import Configuration


class SampleCreateRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'file_name': 'str',
        'thumb_name': 'str',
        'exif': 'dict(str, object)',
        'meta_data': 'SampleMetaData',
        'custom_meta_data': 'CustomSampleMetaData',
        'source_video': 'str',
        'source_video_frame_index': 'float',
        'source_video_frame_timestamp': 'float'
    }

    attribute_map = {
        'file_name': 'fileName',
        'thumb_name': 'thumbName',
        'exif': 'exif',
        'meta_data': 'metaData',
        'custom_meta_data': 'customMetaData',
        'source_video': 'sourceVideo',
        'source_video_frame_index': 'sourceVideoFrameIndex',
        'source_video_frame_timestamp': 'sourceVideoFrameTimestamp'
    }

    def __init__(self, file_name=None, thumb_name=None, exif=None, meta_data=None, custom_meta_data=None, source_video=None, source_video_frame_index=None, source_video_frame_timestamp=None, _configuration=None):  # noqa: E501
        """SampleCreateRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._file_name = None
        self._thumb_name = None
        self._exif = None
        self._meta_data = None
        self._custom_meta_data = None
        self._source_video = None
        self._source_video_frame_index = None
        self._source_video_frame_timestamp = None
        self.discriminator = None

        self.file_name = file_name
        if thumb_name is not None:
            self.thumb_name = thumb_name
        if exif is not None:
            self.exif = exif
        if meta_data is not None:
            self.meta_data = meta_data
        if custom_meta_data is not None:
            self.custom_meta_data = custom_meta_data
        if source_video is not None:
            self.source_video = source_video
        if source_video_frame_index is not None:
            self.source_video_frame_index = source_video_frame_index
        if source_video_frame_timestamp is not None:
            self.source_video_frame_timestamp = source_video_frame_timestamp

    @property
    def file_name(self):
        """Gets the file_name of this SampleCreateRequest.  # noqa: E501


        :return: The file_name of this SampleCreateRequest.  # noqa: E501
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """Sets the file_name of this SampleCreateRequest.


        :param file_name: The file_name of this SampleCreateRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and file_name is None:
            raise ValueError("Invalid value for `file_name`, must not be `None`")  # noqa: E501

        self._file_name = file_name

    @property
    def thumb_name(self):
        """Gets the thumb_name of this SampleCreateRequest.  # noqa: E501


        :return: The thumb_name of this SampleCreateRequest.  # noqa: E501
        :rtype: str
        """
        return self._thumb_name

    @thumb_name.setter
    def thumb_name(self, thumb_name):
        """Sets the thumb_name of this SampleCreateRequest.


        :param thumb_name: The thumb_name of this SampleCreateRequest.  # noqa: E501
        :type: str
        """

        self._thumb_name = thumb_name

    @property
    def exif(self):
        """Gets the exif of this SampleCreateRequest.  # noqa: E501


        :return: The exif of this SampleCreateRequest.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._exif

    @exif.setter
    def exif(self, exif):
        """Sets the exif of this SampleCreateRequest.


        :param exif: The exif of this SampleCreateRequest.  # noqa: E501
        :type: dict(str, object)
        """

        self._exif = exif

    @property
    def meta_data(self):
        """Gets the meta_data of this SampleCreateRequest.  # noqa: E501


        :return: The meta_data of this SampleCreateRequest.  # noqa: E501
        :rtype: SampleMetaData
        """
        return self._meta_data

    @meta_data.setter
    def meta_data(self, meta_data):
        """Sets the meta_data of this SampleCreateRequest.


        :param meta_data: The meta_data of this SampleCreateRequest.  # noqa: E501
        :type: SampleMetaData
        """

        self._meta_data = meta_data

    @property
    def custom_meta_data(self):
        """Gets the custom_meta_data of this SampleCreateRequest.  # noqa: E501


        :return: The custom_meta_data of this SampleCreateRequest.  # noqa: E501
        :rtype: CustomSampleMetaData
        """
        return self._custom_meta_data

    @custom_meta_data.setter
    def custom_meta_data(self, custom_meta_data):
        """Sets the custom_meta_data of this SampleCreateRequest.


        :param custom_meta_data: The custom_meta_data of this SampleCreateRequest.  # noqa: E501
        :type: CustomSampleMetaData
        """

        self._custom_meta_data = custom_meta_data

    @property
    def source_video(self):
        """Gets the source_video of this SampleCreateRequest.  # noqa: E501

        Name of the source video.  # noqa: E501

        :return: The source_video of this SampleCreateRequest.  # noqa: E501
        :rtype: str
        """
        return self._source_video

    @source_video.setter
    def source_video(self, source_video):
        """Sets the source_video of this SampleCreateRequest.

        Name of the source video.  # noqa: E501

        :param source_video: The source_video of this SampleCreateRequest.  # noqa: E501
        :type: str
        """

        self._source_video = source_video

    @property
    def source_video_frame_index(self):
        """Gets the source_video_frame_index of this SampleCreateRequest.  # noqa: E501

        Index of the frame in the source video.  # noqa: E501

        :return: The source_video_frame_index of this SampleCreateRequest.  # noqa: E501
        :rtype: float
        """
        return self._source_video_frame_index

    @source_video_frame_index.setter
    def source_video_frame_index(self, source_video_frame_index):
        """Sets the source_video_frame_index of this SampleCreateRequest.

        Index of the frame in the source video.  # noqa: E501

        :param source_video_frame_index: The source_video_frame_index of this SampleCreateRequest.  # noqa: E501
        :type: float
        """

        self._source_video_frame_index = source_video_frame_index

    @property
    def source_video_frame_timestamp(self):
        """Gets the source_video_frame_timestamp of this SampleCreateRequest.  # noqa: E501

        Timestamp of the frame in the source video.  # noqa: E501

        :return: The source_video_frame_timestamp of this SampleCreateRequest.  # noqa: E501
        :rtype: float
        """
        return self._source_video_frame_timestamp

    @source_video_frame_timestamp.setter
    def source_video_frame_timestamp(self, source_video_frame_timestamp):
        """Sets the source_video_frame_timestamp of this SampleCreateRequest.

        Timestamp of the frame in the source video.  # noqa: E501

        :param source_video_frame_timestamp: The source_video_frame_timestamp of this SampleCreateRequest.  # noqa: E501
        :type: float
        """

        self._source_video_frame_timestamp = source_video_frame_timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SampleCreateRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SampleCreateRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SampleCreateRequest):
            return True

        return self.to_dict() != other.to_dict()
